version: '3'
services:

    db:
      container_name: 'postgres'
      image: postgres
      environment:
        POSTGRES_PASSWORD: WSX1qaz
      ports:
        - "5433:5432"
        # (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/
    
    nginx:
      container_name: 'nginx-container'        
      build: ./nginx
      restart: always
      ports:
        - "8080:80" 
      volumes:        
        - web_data:/docker_code        
        - ./log:/var/log/nginx              
      depends_on:
        - web

    web:
      container_name: 'web-container'
      build: ./website
      #command: python manage.py runserver 0.0.0.0:8000
      command: uwsgi --ini uwsgi.ini 
      restart: always
      volumes:
        - web_data:/docker_code
        # (HOST:CONTAINER)
      ports:
        - "8002:8000"
        # (HOST:CONTAINER)
      depends_on:
        - db
      # command: ["./wait-for-postgres.sh", "db", "python", "app.py"]

volumes:
    web_data:
    pgdata: